export enum EnvVariable {
  COMPANY_NAME = "COMPANY_NAME",
  SERVER_PORT = "SERVER_PORT",
  NODE_ENV = "NODE_ENV",
  JWT_SECRET = "JWT_SECRET",
  DATABASE_URL = "DATABASE_URL",
  LOGGING_DATABASE_URL = "LOGGING_DATABASE_URL",
  REDIS_CACHE_URL = "REDIS_CACHE_URL",
  REDIS_BULLMQ_URL = "REDIS_BULLMQ_URL",
  REDIS_THROTTLE_URL = "REDIS_THROTTLE_URL",
  THROTTLE_TTL_SECOND = "THROTTLE_TTL_SECOND",
  THROTTLE_LIMIT = "THROTTLE_LIMIT",
  MAILGUN_API_KEY = "MAILGUN_API_KEY",
  MAILGUN_DOMAIN = "MAILGUN_DOMAIN",
  COMPANY_EMAIL = "COMPANY_EMAIL",
  ACCOUNT_ACTIVATION_CODE_VALIDITY_DURATION = "ACCOUNT_ACTIVATION_CODE_VALIDITY_DURATION"
}
